services:
  - type: web
    name: developer-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_GTM
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GMAIL_PASSKEY
        sync: false
      - key: EMAIL_ADDRESS
        sync: false
    healthCheckPath: /api/health